# Generated by Django 6.2 on 2026-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
